Vagrant.configure("2") do |config|
    config.vm.define "sql-task13" do |vm|
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = "webserver-01"

        # Налаштування ресурсів для VirtualBox
        vm.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = 2
        end

        # Публічна мережа з динамічним IP
        vm.vm.network "public_network"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y mysql-server
        SHELL
    end
end