Vagrant.configure("2") do |config|
    config.vm.define "Docker" do |vm|
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = "webserver-01"

        # Налаштування ресурсів для VirtualBox
        vm.vm.provider "virtualbox" do |vb|
            vb.memory = "8192"
            vb.cpus = 3
        end

        # Публічна мережа з динамічним IP
        vm.vm.network "public_network"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y
            sudo apt-get update
            sudo apt-get install ca-certificates curl -y
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            sudo docker run hello-world
        SHELL
    end
end