plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_common_args: >-
    {% if 'private' in tags.Name %}
    -o ProxyCommand="ssh -i cources.pem -W %h:%p -q ubuntu@{{ groups['tag_dev-bastion'][0] }}"
    {% endif %}
