Vagrant.configure("2") do |config|
    config.vm.define "webserver" do |vm|
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = "webserver-01"

        # Налаштування ресурсів для VirtualBox
        vm.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
        end

        # Спільна папка
        vm.vm.synced_folder "./shared_vm", "/vagrant_shared"

        # Публічна мережа з динамічним IP
        vm.vm.network "public_network"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y apache2
        SHELL
    end

    config.vm.define "private_server" do |vm|
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = "private-server-02"

        # Налаштування ресурсів для VirtualBox
        vm.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
        end

        # Спільна папка
        vm.vm.synced_folder "./shared_vm", "/vagrant_shared"

        # Публічна мережа з динамічним IP
        vm.vm.network "private_network", ip: "1.1.1.212"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y apache2
        SHELL
    end

    config.vm.define "webserver-3" do |vm|
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = "webserver-03"

        # Налаштування ресурсів для VirtualBox
        vm.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
        end

        # Спільна папка
        vm.vm.synced_folder "./shared_vm", "/vagrant_shared_separately"

        # Публічна мережа з динамічним IP
        vm.vm.network "public_network", bridge: "Realtek Gaming 2.5GbE Family Controller", ip: "1.1.1.213"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y apache2
        SHELL
    end

    # Створення додаткових трьох серверів (webserver-04, webserver-05, webserver-06) без дублювання коду
    (4..6).each do |i|
        config.vm.define "webserver-0#{i}" do |vm|
            vm.vm.box = "bento/ubuntu-24.04"
            vm.vm.hostname = "webserver-0#{i}"

        # Налаштування ресурсів для VirtualBox
            vm.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
                vb.cpus = 1
        end

        # Спільна папка для кожної машини
        vm.vm.synced_folder "./shared_vm", "/vagrant_shared"

        # Публічна мережа зі статичним IP
        vm.vm.network "public_network", ip: "1.1.1.1#{i}"

        # Провізіонінг за допомогою shell-команди
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y apache2
        SHELL
        end
    end

end
